<template>
  <navbar v-if="isUser" @display-search="openModal"></navbar>
  <search-modal @close="closeModal" :display="display"></search-modal>
  <div class="bg-gray-100 text-gray-900 tracking-wider leading-normal">
    <div
      v-if="isUser"
      class="container w-full h-auto flex flex-wrap mx-auto px-2 pt-8 lg:pt-16 mt-2"
    >
      <sidebar v-if="isUser"></sidebar>
      <router-view />
    </div>
    <div v-else>
      <router-view />
    </div>
  </div>
  <Footer v-if="isUser" />
</template>

<script>
import Navbar from "./components/Navbar.vue";
import SearchModal from "./components/SearchModal.vue";
import Sidebar from "./components/Sidebar2.vue";
import Footer from "./components/Footer.vue";

export default {
  data() {
    return {
      open: false,
      menu: [],
      display: false,
      isUser: false,
    };
  },
  components: {
    Navbar,
    Sidebar,
    Footer,
    SearchModal,
  },
  watch: {
    $route(to) {
      if (to.name) {
        if (to.name.toLowerCase().includes("admin")) {
          this.isUser = false;
        } else {
          this.isUser = true;
        }
      } else {
        this.isUser = true;
      }
    },
  },
  methods: {
    openModal() {
      this.display = true;
    },
    closeModal() {
      this.display = false;
    },
  },
};
</script>

<style>
@keyframes ldio-z7lwnyf26q {
  0% {
    top: 48px;
    left: 48px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 24px;
    left: 24px;
    width: 48px;
    height: 48px;
    opacity: 0;
  }
}

.ldio-z7lwnyf26q div {
  position: absolute;
  border-width: 2px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-z7lwnyf26q 0.6711409395973155s cubic-bezier(0, 0.2, 0.8, 1)
    infinite;
}

.ldio-z7lwnyf26q div:nth-child(1) {
  border-color: #34bf49;
}

.ldio-z7lwnyf26q div:nth-child(2) {
  border-color: #34bf49;
  animation-delay: -0.33557046979865773s;
}

.loadingio-spinner-ripple-gorw4pm31tf {
  width: 88px;
  height: 88px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-z7lwnyf26q {
  width: auto;
  height: auto;
  position: relative;
  transform: translateZ(0) scale(0.88);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-z7lwnyf26q div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
