<template>
  <div class="md:flex flex-col md:flex-row md:min-h-screen w-auto bg-gray-200">
    <router-view />
  </div>
</template>

<script>
export default {
  data() {
    return {
      open: false,
    };
  },
  components: {},
  methods: {},
};
</script>

<style>
@keyframes ldio-z7lwnyf26q {
  0% {
    top: 48px;
    left: 48px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 24px;
    left: 24px;
    width: 48px;
    height: 48px;
    opacity: 0;
  }
}

.ldio-z7lwnyf26q div {
  position: absolute;
  border-width: 2px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-z7lwnyf26q 0.6711409395973155s cubic-bezier(0, 0.2, 0.8, 1)
    infinite;
}

.ldio-z7lwnyf26q div:nth-child(1) {
  border-color: #34bf49;
}

.ldio-z7lwnyf26q div:nth-child(2) {
  border-color: #34bf49;
  animation-delay: -0.33557046979865773s;
}

.loadingio-spinner-ripple-gorw4pm31tf {
  width: 88px;
  height: 88px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-z7lwnyf26q {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.88);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-z7lwnyf26q div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
